
apiVersion: apps/v1
kind: Deployment
metadata:
  name: coffee-app-deployment
  labels:
    app: coffee-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: coffee-app
  template:
    metadata:
      labels:
        app: coffee-app
    spec:
      containers:
      - name: coffee-app
        image: mikey6/coffee-club-reg-app:41
        imagePullPolicy: Always
        ports:
        - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: clb-regapp
  labels: 
    app: coffee-app
spec:
  type: LoadBalancer 
  selector:
    app: coffee-app
  ports: 
    - port: 80
      targetPort: 8080
