apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: coffee-app
  name: coffee-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: coffee-app
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: coffee-app
    spec:
      containers:
      - image: mikey6/coffee-club-reg-app:40
        name: coffee-app
        resources: {}
status: {}
---
apiVersion: v1
kind: Service
metadata:
  name: lb-service
  labels:
    app: lb-service
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 5000
  selector:
    app: coffee-app
